# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cggm <- function(W_keys, W_values, W_lassoi, Ri, Ai, pi, ui, S, lambdas, lambda_lasso, eps_lasso, eps_fusions, scale_factor_cpath, scale_factor_lasso, gss_tol, conv_tol, max_iter, store_all_res, refit, refit_lasso, verbose) {
    .Call(`_CGGMR_cggm`, W_keys, W_values, W_lassoi, Ri, Ai, pi, ui, S, lambdas, lambda_lasso, eps_lasso, eps_fusions, scale_factor_cpath, scale_factor_lasso, gss_tol, conv_tol, max_iter, store_all_res, refit, refit_lasso, verbose)
}

.count_clusters <- function(E, n) {
    .Call(`_CGGMR_count_clusters`, E, n)
}

.find_subgraphs <- function(E, n) {
    .Call(`_CGGMR_find_subgraphs`, E, n)
}

.find_mst <- function(G) {
    .Call(`_CGGMR_find_mst`, G)
}

.median_distance <- function(Theta) {
    .Call(`_CGGMR_median_distance`, Theta)
}

.k_largest <- function(vec, k) {
    .Call(`_CGGMR_k_largest`, vec, k)
}

.compute_Theta <- function(R, A, u) {
    .Call(`_CGGMR_compute_Theta`, R, A, u)
}

update_inverse <- function(M_inv, M, k) {
    .Call(`_CGGMR_update_inverse`, M_inv, M, k)
}

.scaled_squared_norms <- function(Theta) {
    .Call(`_CGGMR_scaled_squared_norms`, Theta)
}

.squared_norms <- function(Theta) {
    .Call(`_CGGMR_squared_norms`, Theta)
}

